# Generated by Django 3.2.4 on 2021-06-14 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210615_0234'),
    ]

    operations = [
        migrations.CreateModel(
            name='chat_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Search_model',
        ),
    ]
